src/java/com/udea/model/Weather.java
package com.udea.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Daniel Jaramillo
 */
@Entity
@XmlRootElement
public class Weather implements Serializable {

  private static final long serialVersionUID = 1L;
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private Long id;
  private double temperatura;
  private double porcentaje_hum_rel;
  private String tipo_nubosidad;
  private double prob_precipitaciones;
  private Date dia;
  
  public Long getId() {
    return id;
  }

  public void setId(Long id) {
    this.id = id;
  }

  @Override
  public int hashCode() {
    int hash = 0;
    hash += (id != null ? id.hashCode() : 0);
    return hash;
  }

  /**
   * Get the value of temperatura
   *
   * @return the value of temperatura
   */
  public double getTemperatura() {
    return temperatura;
  }

  /**
   * Set the value of temperatura
   *
   * @param temperatura new value of temperatura
   */
  public void setTemperatura(double temperatura) {
    this.temperatura = temperatura;
  }
  
  /**
   * Get the value of porcentaje_hum_rel
   *
   * @return the value of porcentaje_hum_rel
   */
  public double getPorcentaje_hum_rel() {
    return porcentaje_hum_rel;
  }

  /**
   * Set the value of porcentaje_hum_rel
   *
   * @param porcentaje_hum_rel new value of porcentaje_hum_rel
   */
  public void setPorcentaje_hum_rel(double porcentaje_hum_rel) {
    this.porcentaje_hum_rel = porcentaje_hum_rel;
  }

  /**
   * Get the value of tipo_nubosidad
   *
   * @return the value of tipo_nubosidad
   */
  public String getTipo_nubosidad() {
    return tipo_nubosidad;
  }

  /**
   * Set the value of tipo_nubosidad
   *
   * @param tipo_nubosidad new value of tipo_nubosidad
   */
  public void setTipo_nubosidad(String tipo_nubosidad) {
    this.tipo_nubosidad = tipo_nubosidad;
  }

  /**
   * Get the value of prob_precipitaciones
   *
   * @return the value of prob_precipitaciones
   */
  public double getProb_precipitaciones() {
    return prob_precipitaciones;
  }

  /**
   * Set the value of prob_precipitaciones
   *
   * @param prob_precipitaciones new value of prob_precipitaciones
   */
  public void setProb_precipitaciones(double prob_precipitaciones) {
    this.prob_precipitaciones = prob_precipitaciones;
  }

  /**
   * Get the value of dia
   *
   * @return the value of dia
   */
  public Date getDia() {
    return dia;
  }

  /**
   * Set the value of dia
   *
   * @param dia new value of dia
   */
  public void setDia(Date dia) {
    this.dia = dia;
  }

  @Override
  public boolean equals(Object object) {
    // TODO: Warning - this method won't work in the case the id fields are not set
    if (!(object instanceof Weather)) {
      return false;
    }
    Weather other = (Weather) object;
    if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
      return false;
    }
    return true;
  }

  @Override
  public String toString() {
    return "com.udea.modelo.Weather[ id=" + id + " ]";
  }
  
}

src/java/com/udea/presentation/WeatherController.java
package com.udea.presentation;

import com.udea.model.Weather;
import com.udea.presentation.util.JsfUtil;
import com.udea.presentation.util.PaginationHelper;
import com.udea.facade.WeatherFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;

@Named("weatherController")
@SessionScoped
public class WeatherController implements Serializable {

  private Weather current;
  private DataModel items = null;
  @EJB
  private com.udea.facade.WeatherFacade ejbFacade;
  private PaginationHelper pagination;
  private int selectedItemIndex;

  public WeatherController() {
  }

  public Weather getSelected() {
    if (current == null) {
      current = new Weather();
      selectedItemIndex = -1;
    }
    return current;
  }

  private WeatherFacade getFacade() {
    return ejbFacade;
  }

  public PaginationHelper getPagination() {
    if (pagination == null) {
      pagination = new PaginationHelper(10) {

        @Override
        public int getItemsCount() {
          return getFacade().count();
        }

        @Override
        public DataModel createPageDataModel() {
          return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
        }
      };
    }
    return pagination;
  }

  public String prepareList() {
    recreateModel();
    return "List";
  }

  public String prepareView() {
    current = (Weather) getItems().getRowData();
    selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
    return "View";
  }

  public String prepareCreate() {
    current = new Weather();
    selectedItemIndex = -1;
    return "Create";
  }

  public String create() {
    try {
      getFacade().create(current);
      JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("WeatherCreated"));
      return prepareCreate();
    } catch (Exception e) {
      JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
      return null;
    }
  }

  public String prepareEdit() {
    current = (Weather) getItems().getRowData();
    selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
    return "Edit";
  }

  public String update() {
    try {
      getFacade().edit(current);
      JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("WeatherUpdated"));
      return "View";
    } catch (Exception e) {
      JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
      return null;
    }
  }

  public String destroy() {
    current = (Weather) getItems().getRowData();
    selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
    performDestroy();
    recreatePagination();
    recreateModel();
    return "List";
  }

  public String destroyAndView() {
    performDestroy();
    recreateModel();
    updateCurrentItem();
    if (selectedItemIndex >= 0) {
      return "View";
    } else {
      // all items were removed - go back to list
      recreateModel();
      return "List";
    }
  }

  private void performDestroy() {
    try {
      getFacade().remove(current);
      JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/Bundle").getString("WeatherDeleted"));
    } catch (Exception e) {
      JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
    }
  }

  private void updateCurrentItem() {
    int count = getFacade().count();
    if (selectedItemIndex >= count) {
      // selected index cannot be bigger than number of items:
      selectedItemIndex = count - 1;
      // go to previous page if last page disappeared:
      if (pagination.getPageFirstItem() >= count) {
        pagination.previousPage();
      }
    }
    if (selectedItemIndex >= 0) {
      current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
    }
  }

  public DataModel getItems() {
    if (items == null) {
      items = getPagination().createPageDataModel();
    }
    return items;
  }

  private void recreateModel() {
    items = null;
  }

  private void recreatePagination() {
    pagination = null;
  }

  public String next() {
    getPagination().nextPage();
    recreateModel();
    return "List";
  }

  public String previous() {
    getPagination().previousPage();
    recreateModel();
    return "List";
  }

  public SelectItem[] getItemsAvailableSelectMany() {
    return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
  }

  public SelectItem[] getItemsAvailableSelectOne() {
    return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
  }

  public Weather getWeather(java.lang.Long id) {
    return ejbFacade.find(id);
  }

  @FacesConverter(forClass = Weather.class)
  public static class WeatherControllerConverter implements Converter {

    @Override
    public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
      if (value == null || value.length() == 0) {
        return null;
      }
      WeatherController controller = (WeatherController) facesContext.getApplication().getELResolver().
              getValue(facesContext.getELContext(), null, "weatherController");
      return controller.getWeather(getKey(value));
    }

    java.lang.Long getKey(String value) {
      java.lang.Long key;
      key = Long.valueOf(value);
      return key;
    }

    String getStringKey(java.lang.Long value) {
      StringBuilder sb = new StringBuilder();
      sb.append(value);
      return sb.toString();
    }

    @Override
    public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
      if (object == null) {
        return null;
      }
      if (object instanceof Weather) {
        Weather o = (Weather) object;
        return getStringKey(o.getId());
      } else {
        throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + Weather.class.getName());
      }
    }

  }

}

web/ui/weather/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

  <ui:composition template="/template.xhtml">
    <ui:define name="title">
      <h:outputText value="#{bundle.CreateWeatherTitle}"></h:outputText>
    </ui:define>
    <ui:define name="body">
      <h:panelGroup id="messagePanel" layout="block">
        <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
      </h:panelGroup>
      <h:form>
        <h:panelGrid columns="2">
          <h:outputLabel value="#{bundle.CreateWeatherLabel_id}" for="id" />
          <h:inputText id="id" value="#{weatherController.selected.id}" title="#{bundle.CreateWeatherTitle_id}" />
          <h:outputLabel value="#{bundle.CreateWeatherLabel_temperatura}" for="temperatura" />
          <h:inputText id="temperatura" value="#{weatherController.selected.temperatura}" title="#{bundle.CreateWeatherTitle_temperatura}" />
          <h:outputLabel value="#{bundle.CreateWeatherLabel_porcentaje_hum_rel}" for="porcentaje_hum_rel" />
          <h:inputText id="porcentaje_hum_rel" value="#{weatherController.selected.porcentaje_hum_rel}" title="#{bundle.CreateWeatherTitle_porcentaje_hum_rel}" />
          <h:outputLabel value="#{bundle.CreateWeatherLabel_tipo_nubosidad}" for="tipo_nubosidad" />
          <h:inputText id="tipo_nubosidad" value="#{weatherController.selected.tipo_nubosidad}" title="#{bundle.CreateWeatherTitle_tipo_nubosidad}" />
          <h:outputLabel value="#{bundle.CreateWeatherLabel_prob_precipitaciones}" for="prob_precipitaciones" />
          <h:inputText id="prob_precipitaciones" value="#{weatherController.selected.prob_precipitaciones}" title="#{bundle.CreateWeatherTitle_prob_precipitaciones}" />
          <h:outputLabel value="#{bundle.CreateWeatherLabel_dia}" for="dia" />
          <p:calendar id="dia" value="#{weatherController.selected.dia}" effect="fold" />
        </h:panelGrid>
        <br />
        <h:commandLink action="#{weatherController.create}" value="#{bundle.CreateWeatherSaveLink}" />
        <br />
        <br />
        <h:commandLink action="#{weatherController.prepareList}" value="#{bundle.CreateWeatherShowAllLink}" immediate="true"/>
        <br />
        <br />
        <h:link outcome="/index" value="#{bundle.CreateWeatherIndexLink}"/>
      </h:form>
    </ui:define>
  </ui:composition>

</html>

web/ui/weather/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

  <ui:composition template="/template.xhtml">
    <ui:define name="title">
      <h:outputText value="#{bundle.EditWeatherTitle}"></h:outputText>
    </ui:define>
    <ui:define name="body">
      <h:panelGroup id="messagePanel" layout="block">
        <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
      </h:panelGroup>
      <h:form>
        <h:panelGrid columns="2">
          <h:outputLabel value="#{bundle.EditWeatherLabel_id}" for="id" />
          <h:inputText id="id" value="#{weatherController.selected.id}" title="#{bundle.EditWeatherTitle_id}" />
          <h:outputLabel value="#{bundle.EditWeatherLabel_temperatura}" for="temperatura" />
          <h:inputText id="temperatura" value="#{weatherController.selected.temperatura}" title="#{bundle.EditWeatherTitle_temperatura}" />
          <h:outputLabel value="#{bundle.EditWeatherLabel_porcentaje_hum_rel}" for="porcentaje_hum_rel" />
          <h:inputText id="porcentaje_hum_rel" value="#{weatherController.selected.porcentaje_hum_rel}" title="#{bundle.EditWeatherTitle_porcentaje_hum_rel}" />
          <h:outputLabel value="#{bundle.EditWeatherLabel_tipo_nubosidad}" for="tipo_nubosidad" />
          <h:inputText id="tipo_nubosidad" value="#{weatherController.selected.tipo_nubosidad}" title="#{bundle.EditWeatherTitle_tipo_nubosidad}" />
          <h:outputLabel value="#{bundle.EditWeatherLabel_prob_precipitaciones}" for="prob_precipitaciones" />
          <h:inputText id="prob_precipitaciones" value="#{weatherController.selected.prob_precipitaciones}" title="#{bundle.EditWeatherTitle_prob_precipitaciones}" />
          <h:outputLabel value="#{bundle.EditWeatherLabel_dia}" for="dia" />
          <h:inputText id="dia" value="#{weatherController.selected.dia}" title="#{bundle.EditWeatherTitle_dia}" />
        </h:panelGrid>
        <h:commandLink action="#{weatherController.update}" value="#{bundle.EditWeatherSaveLink}"/>
        <br />
        <br />
        <h:link outcome="View" value="#{bundle.EditWeatherViewLink}"/>
        <br />
        <h:commandLink action="#{weatherController.prepareList}" value="#{bundle.EditWeatherShowAllLink}" immediate="true"/>
        <br />
        <br />
        <h:link outcome="/index" value="#{bundle.EditWeatherIndexLink}" />
      </h:form>
    </ui:define>
  </ui:composition>

</html>

web/ui/weather/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

  <ui:composition template="/template.xhtml">
    <ui:define name="title">
      <h:outputText value="#{bundle.ListWeatherTitle}"></h:outputText>
    </ui:define>
    <ui:define name="body">
      <h:form styleClass="jsfcrud_list_form">
        <h:panelGroup id="messagePanel" layout="block">
          <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
        </h:panelGroup>
        <h:outputText escape="false" value="#{bundle.ListWeatherEmpty}" rendered="#{weatherController.items.rowCount == 0}"/>
        <h:panelGroup rendered="#{weatherController.items.rowCount > 0}">
          <h:outputText value="#{weatherController.pagination.pageFirstItem + 1}..#{weatherController.pagination.pageLastItem + 1}/#{weatherController.pagination.itemsCount}"/>&nbsp;
          <h:commandLink action="#{weatherController.previous}" value="#{bundle.Previous} #{weatherController.pagination.pageSize}" rendered="#{weatherController.pagination.hasPreviousPage}"/>&nbsp;
          <h:commandLink action="#{weatherController.next}" value="#{bundle.Next} #{weatherController.pagination.pageSize}" rendered="#{weatherController.pagination.hasNextPage}"/>&nbsp;
          <h:dataTable value="#{weatherController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
            <h:column>
              <f:facet name="header">
                <h:outputText value="#{bundle.ListWeatherTitle_id}"/>
              </f:facet>
              <h:outputText value="#{item.id}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="#{bundle.ListWeatherTitle_temperatura}"/>
              </f:facet>
              <h:outputText value="#{item.temperatura}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="#{bundle.ListWeatherTitle_porcentaje_hum_rel}"/>
              </f:facet>
              <h:outputText value="#{item.porcentaje_hum_rel}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="#{bundle.ListWeatherTitle_tipo_nubosidad}"/>
              </f:facet>
              <h:outputText value="#{item.tipo_nubosidad}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="#{bundle.ListWeatherTitle_prob_precipitaciones}"/>
              </f:facet>
              <h:outputText value="#{item.prob_precipitaciones}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="#{bundle.ListWeatherTitle_dia}"/>
              </f:facet>
              <h:outputText value="#{item.dia}"/>
            </h:column>
            <h:column>
              <f:facet name="header">
                <h:outputText value="&nbsp;"/>
              </f:facet>
              <h:commandLink action="#{weatherController.prepareView}" value="#{bundle.ListWeatherViewLink}"/>
              <h:outputText value=" "/>
              <h:commandLink action="#{weatherController.prepareEdit}" value="#{bundle.ListWeatherEditLink}"/>
              <h:outputText value=" "/>
              <h:commandLink action="#{weatherController.destroy}" value="#{bundle.ListWeatherDestroyLink}"/>
            </h:column>
          </h:dataTable>
        </h:panelGroup>
        <br />
        <h:commandLink action="#{weatherController.prepareCreate}" value="#{bundle.ListWeatherCreateLink}"/>
        <br />
        <br />
        <h:link outcome="/index" value="#{bundle.ListWeatherIndexLink}"/>
      </h:form>
    </ui:define>
  </ui:composition>

</html>

web/ui/weather/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

  <ui:composition template="/template.xhtml">
    <ui:define name="title">
      <h:outputText value="#{bundle.ViewWeatherTitle}"></h:outputText>
    </ui:define>
    <ui:define name="body">
      <h:panelGroup id="messagePanel" layout="block">
        <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
      </h:panelGroup>
      <h:form>
        <h:panelGrid columns="2">
          <h:outputText value="#{bundle.ViewWeatherLabel_id}"/>
          <h:outputText value="#{weatherController.selected.id}" title="#{bundle.ViewWeatherTitle_id}"/>
          <h:outputText value="#{bundle.ViewWeatherLabel_temperatura}"/>
          <h:outputText value="#{weatherController.selected.temperatura}" title="#{bundle.ViewWeatherTitle_temperatura}"/>
          <h:outputText value="#{bundle.ViewWeatherLabel_porcentaje_hum_rel}"/>
          <h:outputText value="#{weatherController.selected.porcentaje_hum_rel}" title="#{bundle.ViewWeatherTitle_porcentaje_hum_rel}"/>
          <h:outputText value="#{bundle.ViewWeatherLabel_tipo_nubosidad}"/>
          <h:outputText value="#{weatherController.selected.tipo_nubosidad}" title="#{bundle.ViewWeatherTitle_tipo_nubosidad}"/>
          <h:outputText value="#{bundle.ViewWeatherLabel_prob_precipitaciones}"/>
          <h:outputText value="#{weatherController.selected.prob_precipitaciones}" title="#{bundle.ViewWeatherTitle_prob_precipitaciones}"/>
          <h:outputText value="#{bundle.ViewWeatherLabel_dia}"/>
          <h:outputText value="#{weatherController.selected.dia}" title="#{bundle.ViewWeatherTitle_dia}"/>
        </h:panelGrid>
        <br />
        <h:commandLink action="#{weatherController.destroyAndView}" value="#{bundle.ViewWeatherDestroyLink}"/>
        <br />
        <br />
        <h:link outcome="Edit" value="#{bundle.ViewWeatherEditLink}"/>
        <br />
        <h:commandLink action="#{weatherController.prepareCreate}" value="#{bundle.ViewWeatherCreateLink}" />
        <br />
        <h:commandLink action="#{weatherController.prepareList}" value="#{bundle.ViewWeatherShowAllLink}"/>
        <br />
        <br />
        <h:link outcome="/index" value="#{bundle.ViewWeatherIndexLink}"/>

      </h:form>
    </ui:define>
  </ui:composition>

</html>